spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitnessapp
      database: aiactivityfitnessapp

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "*"

kafka:
  topic:
    name: activity-events

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
